version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${API_PORT_EXPOSE:-9000}:9000"
      - "${CONSOLE_PORT_EXPOSE:-9001}:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: ${ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
    command: server --console-address ":9001" /data

